---
title: "Summarize parameter values for SS3 model setups"
date: "`r Sys.Date()`"
output:
  html_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  cache = TRUE,
  autodep = TRUE
)
options("width" = 90)
```

```{r, message=FALSE}
library("ss3models")
library("dplyr")
d <- get_parvalues(system.file("models", package = "ss3models"),
  write_csv = FALSE)
```

```{r}
d[d$Label == "mat50%_fem", "Label"] <- "mat50perc_fem" # or we'll break knitr
d <- select(d, -PRIOR, -PR_type, -SD)
d <- d %>%
  mutate_each(funs(sprintf("%.1f", round(., digits = 1))), LO:HI) %>%
  arrange(Label)
```

In the table at the end, try searching for a particular parameter to filter the table. Click on a column header to sort by that column. Available parameters are:

```{r}
sort(unique(d$Label))
```

Or search by a model setup name to see all parameters for that model setup. Available models are:

```{r}
list_models()
```

```{r, cache=FALSE}
# devtools::install_github('rstudio/DT')
DT::datatable(d, options = list(
  pageLength = 100,
  lengthMenu = c(10, 50, 100, 200, 400)))
```
